config/routes.rb
Translations::Application.routes.draw do
  devise_for :users
  resources :projects do

    member do
      get 'assign_chapters'
      get 'chapter_paragraphs/:chapter', action: :chapter_paragraphs, as: :chapter_paragraphs
      get 'assign_translators'
      get 'assign_reviewers'
      get :translate, constraints: { project_id: /\d/ }
      get :review, constraints: { project_id: /\d/ }
      get :export
    end

    resources :invitations

    resources :translators do
      collection do
        post :assign
      end
    end
    resources :reviewers do
      collection do
        post :assign
      end
    end
  end

  put 'invitations/edit_user', to: "invitations#edit_user"
  match "activate/invitation/:token", to: "invitations#confirm", as: "invitation_confirm", via: :get

  resources :documents do
  	resources :chapters do
  		post :remaining_translators, on: :collection
  		post :remaining_reviewers, on: :collection
  	end
  end
  resources :paragraphs

  resources :users do
  	get :autocomplete_user_name, on: :collection
  end
  resources :translators

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Sample resource route within a namespace:
     namespace :admin do
       # Directs /admin/products/* to Admin::ProductsController
       # (app/controllers/admin/products_controller.rb)
       resources :projects
       get "/" => 'admin#index'
     end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
   root to: 'users#dashboard'

end

app/views/shared/_project.erb
<% unless project.nil? %>
  <div class=project id=project_<%= project.id%>>
    <ul>
      <li class=name><%= link_to project.name, project_path(project) %></li>
      <li class=from><%= project.orig_language_name %></li>
      <li class=to><%= project.language_name %></li>
      <li class=edit>
        <%= link_to t('users.dashboard.edit'), edit_project_path(project) if type == 'admin' %>
        <%= link_to t('users.dashboard.add_translators'), edit_project_path(project) if type == 'admin' %>
        <%= link_to t('users.dashboard.add_reviewers'), edit_project_path(project) if type == 'admin' %>
        <%= link_to t('users.dashboard.translate'), translate_project_path(project)  if type == 'translation' %>
        <%= link_to t('users.dashboard.review'), review_project_path(project) if type == 'review'  %>
        <%= link_to t('users.dashboard.export'), "javascript:void(0);", { class: "export-project",  data: {url: export_project_path(project)} } %>
        <%= link_to t('users.dashboard.delete'), project_path(project), method: :delete, remote: true, confirm: t('users.dashboard.confirm_delete') if type == 'admin'  %>
      </li>
    </ul>
    <div class=clear></div>
  </div>
<% end %>

app/views/shared/_projects.erb
<% if not projects.nil? and projects.count > 0 %>
  <h2><%= title %></h2>
  <div class=projects>
    <ul class=header>
      <li class=name><%= t('users.dashboard.project_name') %></li>
      <li class=from><%= t('users.dashboard.translated_from') %></li>
      <li class=to><%= t('users.dashboard.translated_to') %></li>
      <li class=edit><%= t('users.dashboard.actions') %></li>
    </ul>
    <%= render partial: "shared/project", collection: projects, locals: {type: type} %>
  </div>
<% end %>