config/routes.rb
Translations::Application.routes.draw do
  devise_for :users
  resources :projects do

    member do
      get 'assign_chapters'
      get 'chapter_paragraphs/:chapter', action: :chapter_paragraphs, as: :chapter_paragraphs
      get 'assign_translators'
      get 'assign_reviewers'
      get :translate, constraints: { project_id: /\d/ }
      get :review, constraints: { project_id: /\d/ }
      get :export
    end

    resources :invitations

    resources :translators do
      collection do
        post :assign
      end
    end
    resources :reviewers do
      collection do
        post :assign
      end
    end
  end

  put 'invitations/edit_user', to: "invitations#edit_user"
  match "activate/invitation/:token", to: "invitations#confirm", as: "invitation_confirm", via: :get

  resources :documents do
  	resources :chapters do
  		post :remaining_translators, on: :collection
  		post :remaining_reviewers, on: :collection
  	end
  end
  resources :paragraphs

  resources :users do
  	get :autocomplete_user_name, on: :collection
  end
  resources :translators

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Sample resource route within a namespace:
     namespace :admin do
       # Directs /admin/products/* to Admin::ProductsController
       # (app/controllers/admin/products_controller.rb)
       resources :projects
       get "/" => 'admin#index'
     end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
   root to: 'users#dashboard'

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  attr_accessible :token, :email, :name, :project_id, :role
  attr_reader :emails
  belongs_to :project
  belongs_to :user

  validates_format_of :email,:with => Devise::email_regexp
  validates_uniqueness_of :token

  scope :is_invited?, lambda { |invitation| where(email: invitation.email, project_id: invitation.project_id, role: invitation.role) }
  scope :find_tokens, lambda { |token| where(token: token) }

  after_initialize :generate_hash, :if => :new_record?
  def generate_hash
    self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
  end

  def self.was_invited? invitation
    is_invited?(invitation).present?
  end

  def self.find_token token
    self.find_tokens(token).first
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  skip_before_action :authenticate_user!, raise: false, only: [:confirm]

  def new
    @invitation = Invitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @invitation }
    end
  end

  # create or resend invitation mail
  def create
    @invited=0
    @project = Project.find params.permit(:project_id)
    role= invitation_params[:role]
    invitation_params[:emails].split("\n").each do |e|
      e.strip.split(' ').each do |email|
        @invitation = Invitation.where(email: email, role: role, project_id: @project.id).first
        unless @invitation.present?
          @invitation = @project.invitations.new(email: email, role: role)
          next unless @invitation.save
        end
        @invited += 1
        InvitationMailer.send("%{role}_invitation" % {role: @invitation.role}, @invitation, current_user).deliver
      end
    end

    respond_to do |format|
      if @invited.size > 0
        format.html { redirect_to(@project) }
        format.js
      else
        format.html { render action: 'new' }
        format.js
      end
    end
  end

  # Confirm token sent by mail as an invitation to project
  def confirm
    (redirect_to(root_url); return) unless params.permit(:token).present?
    @invitation = Invitation.find_token(params.permit(:token).to_s)

    unless @invitation
      redirect_to root_url, flash: {error: t('invitations.confirm.invalid_token')}
      return
    end

    @user = User.where(email: @invitation.email).first
    @project = Project.find @invitation.project_id

    # create user
    unless @user.present?
      name = @invitation.email.split('@').first.capitalize
      pass = SecureRandom.hex(8)
      @user = User.new(email: @invitation.email, name: name, password: pass, password_confirmation: pass)
      @user.confirm!
      (redirect_to(root_path); return) unless @user.save
    end

    # include in the project as :role
    @project.send(@invitation.role+"s_users") << @user
    @project.save

    sign_in @user
    @invitation.destroy
    InvitationMailer.notice_admin_of_new_user(@project, @user).deliver
    flash[:notice] = t("invitations.confirm.notice_account_activated")
  end

  def edit_user
    if current_user
      current_user.update_attributes params.permit(:user)
      flash[:notice] = t("invitations.edit_user.user_profile_saved")
    else
      flash[:error] = t("invitations.edit_user.not_loggedin")
    end
      (redirect_to(root_path); return)
  end

  protected

  def invitation_params
    params.require(:invitation).permit([:emails, :role])
  end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/confirm.erb
<h2>Edit <%= @user.to_s.humanize %></h2>

<%= form_for(@user, :url => invitations_edit_user_path, :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :name %><br />
  <%= f.text_field :name, :autofocus => true %></div>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password, :autocomplete => "off" %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

<div><%= f.submit "Update", {class: "btn btn-primary"} %></div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(@user), :data => { :confirm => "Are you sure?" }, :method => :delete %></p>

<%= link_to "Back", :back %>

app/views/invitations/create.js.erb
<% if @invited %>
		$('#invitation-response').html("<p class=success><%= t('projects.assign_translators.invited_with_success') %></p>").fadeIn().delay(3000).fadeOut();
<% else %>
		$('#invitation-response').html("<p class=fail><%= t('projects.assign_translators.invitation_failed') %></p>").fadeIn().delay(3000).fadeOut();
<% end %>

$('#people_invited').val('');