config/routes.rb
Translations::Application.routes.draw do
  devise_for :users
  resources :projects do

    member do
      get 'assign_chapters'
      get 'chapter_paragraphs/:chapter', action: :chapter_paragraphs, as: :chapter_paragraphs
      get 'assign_translators'
      get 'assign_reviewers'
      get :translate, constraints: { project_id: /\d/ }
      get :review, constraints: { project_id: /\d/ }
      get :export
    end

    resources :invitations

    resources :translators do
      collection do
        post :assign
      end
    end
    resources :reviewers do
      collection do
        post :assign
      end
    end
  end

  put 'invitations/edit_user', to: "invitations#edit_user"
  match "activate/invitation/:token", to: "invitations#confirm", as: "invitation_confirm", via: :get

  resources :documents do
  	resources :chapters do
  		post :remaining_translators, on: :collection
  		post :remaining_reviewers, on: :collection
  	end
  end
  resources :paragraphs

  resources :users do
  	get :autocomplete_user_name, on: :collection
  end
  resources :translators

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Sample resource route within a namespace:
     namespace :admin do
       # Directs /admin/products/* to Admin::ProductsController
       # (app/controllers/admin/products_controller.rb)
       resources :projects
       get "/" => 'admin#index'
     end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
   root to: 'users#dashboard'

end

app/models/project.rb
# encoding: utf-8
class Project < ApplicationRecord
  belongs_to :owner, :class_name => 'User'
  belongs_to :to_language, :class_name => 'Language'
  belongs_to :from_language, :class_name => 'Language'
  belongs_to :to_document, :class_name => 'Document', required: false
  belongs_to :from_document, :class_name => 'Document', required: false
  has_many   :from_paragraphs, through: :from_document, :source => 'paragraphs'
  has_many   :to_paragraphs, through: :to_document, :source => 'paragraphs'
  has_many   :translators
  has_many   :translators_users, through: :translators, source: 'user' do
    def <<(new_item)
      super( Array(new_item) - proxy_association.owner.translators_users )
    end
  end
  has_many   :reviewers
  has_many   :reviewers_users, through: :reviewers, source: 'user' do
    def <<(new_item)
      super( Array(new_item) - proxy_association.owner.reviewers_users )
    end
  end
  has_many   :invitations

  #scope :grouped_paragraphs, from_paragraphs.select(['paragraphs.id', 'paragraphs.text', 'paragraphs.chapter']).group(:chapter)
  has_attached_file :source_filename

  validates_attachment_presence :source_filename
  validates_attachment_size :source_filename, :less_than => 100.megabytes
  validates_attachment_content_type :source_filename, content_type: ['application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']

  validates_presence_of :from_language_id
  validate :different_languages

  before_create :build_documents
  after_create_commit :import_document

  def build_documents
    self.create_from_document! :language_id => from_language_id
    self.create_to_document! :language_id => to_language_id
  end
  def import_document
    doc = Docx::Document.open(source_filename.path)
    chapter_order = 1
    paragraph_order = 0
    chapter_words = ["capítulo", "parte"]
    debugger
    chapter = Chapter.create! document_id: from_document_id, order: chapter_order, name: 'introduction'
    doc.paragraphs.each do |p|
      #TODO fix for any language
      if p.to_s.size < 50
      	p_down = p.to_s.downcase
      	chapter_words.each do |word|
      	  if p_down.include? word
            chapter = Chapter.create! document_id: from_document_id, order: chapter_order, name: p.text
            chapter_order += 1
      	  	break
      	  end
      	end
      end
      Paragraph.create!(:text => p.to_s, :status => 'original', :chapter_id => chapter.id, :order => paragraph_order, :document_id => from_document_id)
      Paragraph.create!(:text => '', :status => 'empty', :chapter_id => chapter.id, :order => paragraph_order, :document_id => to_document_id)
      paragraph_order += 1
    end
  end

  def orig_language_name
    self.from_language.nil? ? '' : self.from_language.name
  end
  def language_name
    self.to_language.nil? ? '' : self.to_language.name
  end

  def is_article?
    self.content_type == 'article'
  end
  def is_book?
    self.content_type == 'book'
  end

  def can_have_chapters?
    ['book'].include? self.content_type
  end

  protected

  #TODO: fix message translation
  def different_languages
    if self.from_language_id == self.to_language_id
      self.errors[:different_languages] << "languages need to be different"
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, :except => [:new, :create, :index]

  def new
    @project = Project.new
    @languages = Language.all
  end

  def create
    @project = Project.new(project_params)
    @project.owner_id = current_user.id

    respond_to do |wants|
      if @project.save
        flash[:notice] = t('projects.create.project_created')
        wants.html { redirect_to(assign_chapters_project_path(@project)) }
      else
        @languages = Language.all
        wants.html { render :action => "new" }
      end
    end
  end

  def index
    @projects = Project.all
  end

  def show
    respond_to do |wants|
      wants.html # show.html.erb
      wants.xml  { render :xml => @project }
    end
  end

  def edit
  	  authorize @project
  end
  def assign_chapters
  	authorize @project
    redirect_to assign_translators_project_path(@project) unless @project.can_have_chapters?
  end

  def chapter_paragraphs
    @paragraphs = @project.from_paragraphs.in_chapter params[:chapter]
  end

  def assign_translators
  	authorize @project
    @translators = @project.translators
    @invitation = Invitation.new
    @unassigned_chapters = Chapter.t_remaining @project.from_document_id
  end

  def assign_reviewers
  	authorize @project
    @reviewers = @project.reviewers
    @invitation = Invitation.new
    @unassigned_chapters = Chapter.r_remaining @project.from_document_id
  end

  def translate
  	authorize @project
    #page = params[:page].present? ? params[:page] : 1
    @f_paragraphs = @project.from_paragraphs.page(params[:page])
    @t_paragraphs = @project.to_paragraphs.page(params[:page])
  end

  def review
  	authorize @project
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |wants|
      wants.html { redirect_to(projects_url) }
      wants.js  { }
    end
  end

  private

  def project_params
    params.require(:project).permit(:owner_id, :to_language_id, :from_language_id, :from_document_id, :to_document_id, :source_filename, :name, :content_type)
  end

  def find_project
    if not params[:id].nil? and Project.exists?(params[:id])
    @project = Project.find params[:id]
    else
      flash[:error] = t("Unable to find model with ID #{params[:id]}!")
      redirect_to projects_path
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_sidebar.erb
  <div id="<%= type %>">
    <h3><%= t('.'+type+'_assigned') %></h3>
    <% people = @project.send(type, true) %>
    <% if people.blank? %>
       <%= t('.no_assignees') %>
  	<% end %>
    <% people.each do |person| %>
      <%= person.name %>
      <ul>
        <% person.chapters.each do |chapter| %>
          <li><%= chapter.order_n_name %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div id="missing-chapters">
    <h3><%= t('.unassigned_chapters') %></h3>
    <ul>
      <% @unassigned_chapters.each do |chapter| %>
        <li><%= chapter.order_n_name %></li>
      <% end %>
    </ul>
  </div>

app/views/projects/_steps_menu.erb
<% action = params[:action] %>
<div class=menu>
  <div class="block <%= "selected" if action == 'new' %>"> <%= t('.create_a_project') %></div>
  <div class="block <%= "selected" if action == 'assign_chapters' %>"> <%= t('.define_chapters') %></div>
  <div class="block <%= "selected" if action == 'assign_translators' %>"> <%= t('.assign_translators') %></div>
  <div class="block <%= "selected" if action == 'assign_reviewers' %>"> <%= t('.assign_reviewers') %></div>
</div>

app/views/projects/assign_chapters.erb
<div id="project">

  <%= render partial: 'steps_menu' %>

  <div class="step">
    <h1><%= t('.assign_chapters') %></h1>
    <p><%= t('.assign_chapters_instructions') %></p>
    <div id="chapters">
      <% @project.from_document.chapters.each do |chapter| %>
        <div class="chapter-number">
          <%= t('.chapter_number') %>
          <strong> <%= chapter.id %> </strong>
        </div>
        <% klass = 'chapter-title' %>
        <% chapter.paragraphs.each do |p| %>
          <% if p.text.strip.size > 1 %>
            <%= content_tag 'div', class: 'chapter '+klass, data: {url: chapter_paragraphs_project_path(@project, chapter.id)}  do %>
              <%= p.text %>
            <% end %>
            <% klass='' %>
            <div id="chapter_1_content" style="display:none">
              <%= t('.loading_content') %>
            </div>
          <% end %>
        <% end %>
          <div class=clear></div>
      <% end %>
    </div>
  </div>
  <%= link_to t('.forward'), assign_translators_project_path(@project), :class => 'arrow-right right' %>
</div>

app/views/projects/assign_reviewers.erb
<div id="project">

  <%= render partial: 'steps_menu' %>

  <div class="step reviewers">
    <div class=body>
      <div class=head>
        <h2> <%= t('.assign_reviewers') %> </h2>
        <div><%= t('.look_for_registered_users') %></div>
      </div>

      <%= text_field_tag :person_tokens, '', { autofocus: true, class: "typeahead", 'data-url' => autocomplete_user_name_users_path } %>
      <div id="person-chapters" data-url="<%= remaining_reviewers_document_chapters_path @project.from_document %>" > </div>
      <div id="person-response"> </div>
      <div class=clear></div>

      <%= form_for [@project, @invitation], remote: true do |f| %>

        <div class=head>
          <h4 class=action> <%= t('projects.assign_chapters.invite_someone') %> </h4>
        </div>
        <div class=invitation>
          <div><%= t('.write_email_by_line') %></div>
          <%= f.text_area :emails, :id => 'people_invited', rows: 8 %>
          <%= f.hidden_field :role, value: "reviewer" %>
          <div><%= t('.a_mail_will_be_sent') %></div>
          <%= f.submit t('.send_invitations'), class: "btn btn-primary" %>
          <div id="invitation-response"> </div>
        </div>
        <div class=clear></div>

      <% end %>
      <%= link_to t('projects.assign_reviewers.finish'), project_path(@project), :class => 'arrow-right right' %>
    </div>
    <div class="sidebar">
      <%= render partial: 'sidebar', locals: {type: 'reviewers'} %>
    </div>
    <div class="clear"> </div>

    </div>
  </div>
</div>

app/views/projects/assign_translators.erb
<div id="project">

  <%= render partial: 'steps_menu' %>

  <div class="step translators .container">
    <div class=body>
      <div class=head>
        <h2> <%= t('.assign_translators') %> </h2>
        <div><%= t('.look_for_registered_users') %></div>
      </div>

      <%= text_field_tag :person_tokens, '', { autofocus: true, class: "typeahead", 'data-url' => autocomplete_user_name_users_path } %>
      <div id="person-chapters" data-url="<%= remaining_translators_document_chapters_path @project.from_document %>" > </div>
      <div id="person-response"> </div>
      <div class=clear></div>

      <%= form_for [@project, @invitation], {remote: true} do |f| %>

        <div class=head>
          <h4 class=action> <%= t('projects.assign_chapters.invite_someone') %> </h4>
        </div>
        <div class="invitation form-group">
          <div><%= t('.write_email_by_line') %></div>
          <%= f.text_area :emails, :id => 'people_invited', rows: 8 %>
          <%= f.hidden_field :role, value: "translator" %>
          <div><%= t('.a_mail_will_be_sent') %></div>
          <%= f.submit t('.send_invitations'), {class: "btn btn-primary"} %>
          <div id="invitation-response"> </div>
        </div>
        <div class=clear></div>

      <% end %>
      <%= link_to t('projects.assign_translators.go_forward'), assign_reviewers_project_path(@project), :class => 'arrow-right right' %>
    </div>
    <div class="sidebar">
      <%= render partial: 'sidebar', locals: {type: 'translators'} %>
    </div>
    <div class="clear"> </div>

    </div>
  </div>
</div>

app/views/projects/chapter_paragraphs.erb
<% @paragraphs.each do |p| %>
	<div><%= p.text %></div>
<% end %>

app/views/projects/chapter_paragraphs.js.erb
<% @paragraphs.each do |p| %>
	<% if (p.text.strip.size > 0) %>
		<a class=paragraph href alt=""><%= p.text %></a>
	<% end %>
<% end %>

app/views/projects/destroy.js.erb
jQuery('#project_<%= @project.id %>').remove();

app/views/projects/index.erb
<h1>All the projects on this site</h1>

<div id=projects>
  <%= render partial: "shared/projects", locals: {projects: @projects, title: t('projects.index.projects'), type: "general" } %>
</div>

app/views/projects/new.erb
<div id="project">

  <%= render partial: 'steps_menu' %>
  <%= form_for @project, {class: "form-horizontal"} do |f| %>
    <% if @project.errors.any? %>
      <div class=error_messages>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg.to_s %></li>
        <% end %>
        <% @project.from_document && @project.from_document.errors.full_messages.each do |msg| %>
          <li><%= msg.to_s %></li>
        <% end %>
        <% @project.to_document && @project.to_document.errors.full_messages.each do |msg| %>
          <li><%= msg.to_s %></li>
        <% end %>
      </div>
    <% end %>

	<div class="form-group col-xs-7">
    	<%= f.label :name, t('.name'), {class: "control-label col-xs-5"} %>
    	<div class="col-xs-7">
    		<%= f.text_field :name, {class: "form-control"} %>
    	</div>

    	<%= f.label :source_filename, t('.choose_a_file'), {class: "control-label col-xs-5"} %>
    	<div class="col-xs-7">
    		<%= f.file_field :source_filename, {class: "form-control"}  %>
    	</div>

    	<%= f.label :from_language, t('.original_language_of_the_document'), {class: "control-label col-xs-5"} %>
    	<div class="col-xs-7">
    	<%= collection_select :project, :from_language_id, @languages, :id, :name_abbrev %>
    	</div>

    	<%= f.label :to_language, t('.destination_language_of_the_document'), {class: "control-label col-xs-5"} %>
    	<div class="col-xs-7">
    	<%= collection_select :project, :to_language_id, @languages, :id, :name_abbrev %>
    	</div>

    	<%= label :content_type, t('.content_type'), {class: "control-label col-xs-5"} %>
    	<div class="radio col-xs-7">
      	  <%= f.radio_button :content_type, 'book', checked: true %>
      	  <%= f.label :content_type, t('.book') %>
      	  <%= f.radio_button :content_type, t('.article') %>
      	  <%= f.label :content_type, t('.article') %>
    	</div>

	</div>
      <div class="clear"></div>

	<div class="form-group col-xs-7">
    	<%= f.submit "submit", {class: "btn btn-primary"}  %>
	</div>

  <% end %>
</div>

app/views/projects/show.erb
<h1><%= @project.name %></h1>

<% @project.from_document.paragraphs.each do |p| %>
  <p>
    <%= p.text %>
  </p>
<% end %>

app/views/projects/translate.erb
<div id="project">

</div><h1><%= t('.translating', {project: @project.name}) %></h1>

<div id="paragraphs">
  <div class="page">
    <%= render 'paragraphs/paragraphs' %>
  </div>
</div>
<%= paginate @f_paragraphs %>

app/views/projects/translate.js.erb
# app/views/posts/index.js.erb
$("#paragraphs").append("<div class='page'><%= escape_javascript(render(@paragraphs)) %></div>");