config/routes.rb
Translations::Application.routes.draw do
  devise_for :users
  resources :projects do

    member do
      get 'assign_chapters'
      get 'chapter_paragraphs/:chapter', action: :chapter_paragraphs, as: :chapter_paragraphs
      get 'assign_translators'
      get 'assign_reviewers'
      get :translate, constraints: { project_id: /\d/ }
      get :review, constraints: { project_id: /\d/ }
      get :export
    end

    resources :invitations

    resources :translators do
      collection do
        post :assign
      end
    end
    resources :reviewers do
      collection do
        post :assign
      end
    end
  end

  put 'invitations/edit_user', to: "invitations#edit_user"
  match "activate/invitation/:token", to: "invitations#confirm", as: "invitation_confirm", via: :get

  resources :documents do
  	resources :chapters do
  		post :remaining_translators, on: :collection
  		post :remaining_reviewers, on: :collection
  	end
  end
  resources :paragraphs

  resources :users do
  	get :autocomplete_user_name, on: :collection
  end
  resources :translators

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Sample resource route within a namespace:
     namespace :admin do
       # Directs /admin/products/* to Admin::ProductsController
       # (app/controllers/admin/products_controller.rb)
       resources :projects
       get "/" => 'admin#index'
     end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
   root to: 'users#dashboard'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> AM Translations</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
  <link href="http://fonts.googleapis.com/css?family=Lora:400italic,700italic,400,700%7CSource+Sans+Pro:400italic,700italic,400,700%7CSource+Code+Pro" rel="stylesheet" type="text/css">
</head>
<body>
  <header>
    <div class=title><%= link_to 'AM Translations', root_path %></div>
    <div class=menu>
      <ul>
        <li><%= link_to t('layouts.application.all_projects'), projects_path %></li>
        <li><%= link_to t('layouts.application.create_a_project'), new_project_path %></li>
        <%# if can? :manage %>
          <%= link_to t('admin'), admin_path %>
        <%# end %>
      </ul>
    </div>
    <nav id=userinfo>
      <% if user_signed_in? %>
        <%= link_to current_user.name, edit_user_path(current_user) %>
        <%= link_to t('.sign_out'), destroy_user_session_path, :method => :delete %>
      <% end %>
    </nav>
  </header>

  <% unless notice.blank? %>
    <p class="notice"><%= notice %></p>
    <script type="text/javascript">$('.notice').delay(2000).fadeOut('slow');</script>
  <% end %>
  <% unless alert.blank? %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%# if not user_signed_in? %>
  <div id=main>
    <%= yield %>
  </div>

  <footer>
  <%= t('.licensed') %>
  <%= link_to '(AGPL).', 'http://www.gnu.org/licenses/agpl-3.0.html' %>
    <%= t('.download') %>
    <a href="https://gitlab.com/hugomelo/am-translations">GitLab</a>
  </footer>

</body>
</html>